services:
  postgres:
    image: postgres:16
    container_name: parking-postgres
    environment:
      POSTGRES_USER: parking
      POSTGRES_PASSWORD: parking
      POSTGRES_DB: parking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: parking-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata: {}
  mongodata: {}